### PR TITLE
Rust disk-only computation test

### PR DESCRIPTION
**Pull request by datdenkikniet**
This is on top of #21.

Seeing if getting the memory size down by never storing many full cubes and instead streaming them from and to disk in memory is effective or not. Am comparing to points-list with size16, since that seems like it had a pretty small footprint. Important to see if the tradeoff between memory usage and slowdown (I'm fairly sure this will be a tad slower) is worth it.

Results so far (definitely far less memory used :D):

|Implementation   |N = 12    | N=13  |
|:-------------------------|:------------|:---------|
|Disk-only                |500 MB |3.6 GB |
|points-list (size16)|1.2GB    |9.3 GB |

TODO:
- [ ] Figure out what to do on collisions (probably easily solved by associating a file offset with a specific hash, and doing a lookup that way). Note for the future: just using the offset in the file as the hash value may be a valid strategy? Lookups may be slow, but at least very easy. Worth trying
- [ ] Don't immediately start overwriting the file for N = X when starting for that N

### CODE REVIEW

**Comment by NailLegProcessorDivide** [comment]
Interesting strategy and looks like a good potential saving.
Doesnt change anything in your testing but just as an fyi size16 only effects opti-bit-set not point-list

**Comment by datdenkikniet** [comment]
Yeah! Just storing a few extra copies of a specific canonical expansion and filtering them out later on sounds like a good alternative when it comes to memory usage (will use a bunch more disk though, but that should be fine)

**Comment by bertie2** [comment]
@datdenkikniet can this be updated or closed ?

**Comment by datdenkikniet** [comment]
I will close this until I get around to trying this out again :)

**Pull request closed without merging**
